# Generated by Django 4.2 on 2024-04-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessages',
            name='attachment_code',
            field=models.CharField(choices=[('file', 'file'), ('audio', 'audio')], max_length=30, null=True),
        ),
    ]
