# Generated by Django 4.2 on 2024-04-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_chatmessages_attachment_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessages',
            name='attachment_code',
            field=models.CharField(choices=[('FILE', 'file'), ('AUDIO', 'audio')], max_length=30, null=True),
        ),
    ]
