# Generated by Django 4.2 on 2024-04-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_alter_chatmessages_attachment_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='viewed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
