# Generated by Django 4.2 on 2024-05-02 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_chat_viewed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessages',
            name='to_user',
        ),
    ]
