# Generated by Django 4.2 on 2024-05-23 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0007_alter_chatmessages_from_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatMessages',
            new_name='ChatMessage',
        ),
        migrations.CreateModel(
            name='ChatOnlineUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_online_users',
            },
        ),
    ]
