# Generated by Django 4.2 on 2024-05-23 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0009_chatonlineuser_created_at_chatonlineuser_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatOnlineUser',
        ),
    ]
