# Generated by Django 4.2 on 2024-04-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.TextField()),
                ('duration', models.FloatField()),
            ],
            options={
                'db_table': 'audio_attachments',
            },
        ),
        migrations.AlterModelTable(
            name='fileattachment',
            table='file_attachments',
        ),
    ]
