# Generated by Django 4.2 on 2024-04-25 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0002_audioattachment_alter_fileattachment_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileattachment',
            old_name='type',
            new_name='content_type',
        ),
    ]
